CarRent/CarRent/Controllers/ManagerEditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using DataBase;
using Entities;
using Microsoft.AspNet.Identity.EntityFramework;
using CarRent.ViewModels;

namespace CarRent.Controllers
{
    [Authorize(Roles ="admin")]
    public class ManagerEditController : Controller
    {
        private readonly DB DB;

        public ManagerEditController(DB Db)
        {
            DB = Db;
        }
        public ManagerEditController()
        {
            DB = new DB();
        }

        private ApplicationUserManager _userManager;

        public ManagerEditController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index()
        {
            var users = (DB.GetUsers() as IEnumerable<ApplicationUser>).ToList();
            var managers = new List<ManagerRegisterViewModel>();

            if (users == null)
                users = new List<ApplicationUser>();
          
            using(var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(DB.GetContext())))
            {
                foreach (var user in users)
                {
                    var managerViewModel = new ManagerRegisterViewModel()
                    {
                        Email = user.Email,
                        FirstName = user.FirstName,
                        LastName = user.LastName,
                        ManagerID = user.Id
                    };

                    if (UserManager.IsInRole(user.Id, "moderator"))
                    {
                        managers.Add(managerViewModel);
                    }

                    
                };            
            }
            return View(managers);
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(ManagerRegisterViewModel viewModel)
        {
            var manager = new ApplicationUser()
            {
                Email = viewModel.Email,
                FirstName = viewModel.FirstName,
                LastName = viewModel.LastName
            };

            if(manager != null && ModelState.IsValid)
            {
                manager.BirthDate = DateTime.Now.AddYears(-100);
                manager.DrivingLicenseDate = DateTime.Now;
                manager.UserName = viewModel.Email;
                manager.EmailConfirmed = true;
                manager.PhoneNumberConfirmed = true;
               
                var test =  UserManager.Create(manager, viewModel.Password);
                var userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(DB.GetContext()));

                userManager.AddToRole(manager.Id, "moderator");

                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("Email", "This email is already takken");
                return View(viewModel);
            }
        }

        public ActionResult Delete(string id)
        {
            var user = DB.GetEntityById<ApplicationUser>(id) as ApplicationUser;
            if (user != null)
            {
                var manager = new ManagerRegisterViewModel()
                {
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    ManagerID = user.Id
                };

                return View(manager);
            }
            else
            {
                return RedirectToAction("ManagerNotFound", "Error");
            }
        }

        [HttpGet]
        public ActionResult DeleteConfirmed(string id)
        {
            var user = DB.GetEntityById<ApplicationUser>(id) as ApplicationUser;
            if (user != null)
            {
                DB.Delete<ApplicationUser>(user);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("ManagerNotFound", "Error");
            }
            
        }
    } 
}

CarRent/CarRent/Views/ManagerEdit/Delete.cshtml
@model CarRent.ViewModels.ManagerRegisterViewModel
@{ 
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>Are you sure you want to delete this manager?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    Are you sure you want to delete this manager?<br />

    @Html.ActionLink("Yes", "DeleteConfirmed", new { id = Model.ManagerID })
    @Html.ActionLink("No", "Index")
</p>

CarRent/CarRent/Views/ManagerEdit/Index.cshtml
@model IEnumerable<CarRent.ViewModels.ManagerRegisterViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>List of managers</h2>

<p>
    @Html.ActionLink("Create New", "Register")
</p>
<table class="table" style="width:40%";>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>     
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>      
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>      
        <td>
            @Html.ActionLink("Delete", "Delete", new { id=item.ManagerID })
        </td>
    </tr>
}

</table>

CarRent/CarRent/Views/ManagerEdit/Register.cshtml
@model CarRent.ViewModels.ManagerRegisterViewModel
@{
    ViewBag.Title = "Register new manager";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Register", "ManagerEdit", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.FirstName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.LastName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}