CarRent/CarRent/Controllers/CarController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using DataBase;
using CarRent.ViewModels;
using System.IO;
using System.Web.Helpers;
using System.Collections.Generic;

namespace CarRent.Controllers
{
    [Authorize(Roles = "admin")]
    public class CarController : Controller
    {
        private readonly DB DB;

        public CarController(DB Db)
        {
            DB = Db;
        }
        public CarController()
        {
            DB = new DB();
        }

        public ActionResult Index(string search, bool? showArchive)
        {
            return View();
        }

        public ActionResult GetCarList(string search, bool? showArchive)
        {
            var cars = DB.GetList<Car>();

            if (showArchive == true)
            {
                cars = cars.OrderBy(c => c.Archived).ToList();
            }
            else if (showArchive == null || showArchive == false)
            {
                cars = cars.Where(c => c.Archived == false).ToList();
            }

            if (!String.IsNullOrEmpty(search))
            {
                cars = cars.Where(c => c.Brand.Contains(search) || c.Model.Contains(search)).ToList();
            }

            var viewModels = new List<CarListAdminViewModel>();
            foreach (var car in cars)
            {
                var pricing = (DB.GetList<CarTimePricing>()).SingleOrDefault(p => p.CarID == car.ID);
                bool hasValue;
                if (pricing == null)
                    hasValue = false;
                else
                    hasValue = true;

                viewModels.Add(new CarListAdminViewModel()
                {
                    Car = car,
                    HasPricing = hasValue
                });

            }
            
            return PartialView(viewModels);
        }


        [HttpGet]
        public ActionResult Create()
        {
            CarCreateViewModel carCreateViewModel = new CarCreateViewModel()
            {
                BrandsList = new SelectList(Enumerations.Brands.OrderBy(b =>b)),
                EngineTypes = new SelectList(Enumerations.EngineTypes),
                TransmissionTypes = new SelectList(Enumerations.TransmissionTypes),
                GradeList = new SelectList(Enumerations.Grades)
            };

            return View(carCreateViewModel);
        }

        [HttpPost]
        public ActionResult Create(CarCreateViewModel carCreateViewModel, HttpPostedFileBase file)
        {
            if (file != null)
            {
                if (ValidateFile(file))
                {
                    try
                    {
                        SaveFileToDisk(file);
                    }
                    catch (Exception)
                    {
                        ModelState.AddModelError("FileName", "An error occured, try again");
                    }
                }
                else
                {
                    ModelState.AddModelError("FileName", "The file must be gif, png, jpeg or jpg amd less than 2MB");
                }
            }
            else
            {
                ModelState.AddModelError("FileName", "Please choose a file");
            }

            if (ModelState.IsValid)
            {
                Car car = new Car()
                {
                    Brand = carCreateViewModel.Brand,
                    Grade = carCreateViewModel.SelectedGrade,
                    DoorCount = carCreateViewModel.DoorCount,
                    EngineType = carCreateViewModel.SelectedEngineType,
                    FuelConsumption = carCreateViewModel.FuelConsumption,
                    HasAirConditioning = carCreateViewModel.HasAirConditioning,
                    LuggageCount = carCreateViewModel.LuggageCount,
                    Model = carCreateViewModel.Model,
                    PassangerCount = carCreateViewModel.PassangerCount,
                    TransmissionType = carCreateViewModel.SelectedTransmissionType,
                    FileName = file.FileName,
                    BrandModel = carCreateViewModel.Brand + " " +  carCreateViewModel.Model
                };

                DB.Save<Car>(car);

                return RedirectToAction("Index");
            }
            else
            {
                carCreateViewModel.BrandsList = new SelectList(DB.GetList<Brand>().ToList(), "ID", "Name");
                return View(carCreateViewModel);
            }
        }

        [HttpGet]
        public ActionResult Edit(string idUrl)
        {        
            try
            {
                int id = int.Parse(idUrl);

                var car = DB.GetEntityById<Car>(id) as Car;

                if (car != null)
                {
                    CarCreateViewModel carCreateViewModel = new CarCreateViewModel()
                    {
                        CarID = id,
                        Brand = car.Brand,
                        BrandsList = new SelectList(Enumerations.Brands.OrderBy(b => b)),
                        TransmissionTypes = new SelectList(Enumerations.TransmissionTypes),
                        EngineTypes = new SelectList(Enumerations.EngineTypes),
                        GradeList = new SelectList(Enumerations.Grades),
                        SelectedGrade = car.Grade,
                        DoorCount = car.DoorCount,
                        FileName = car.FileName,
                        FuelConsumption = car.FuelConsumption,
                        HasAirConditioning = car.HasAirConditioning,
                        LuggageCount = car.LuggageCount,
                        Model = car.Model,
                        PassangerCount = car.PassangerCount,
                        SelectedEngineType = car.EngineType,
                        SelectedTransmissionType = car.TransmissionType
                    };

                    return View(carCreateViewModel);
                }
                else
                {
                    return RedirectToAction("CarNotFound", "Error");
                }
            }
            catch (ArgumentException)
            {
                return RedirectToAction("WrongUrl", "Error");
            }
            catch (FormatException)
            {
                return RedirectToAction("WrongUrl", "Error");
            }
        }

        [HttpPost]
        public ActionResult Edit(CarCreateViewModel carCreateViewModel, HttpPostedFileBase file)
        {
            if (file != null)
            {
                if (ValidateFile(file))
                {
                    try
                    {
                        SaveFileToDisk(file);
                    }
                    catch (Exception)
                    {
                        ModelState.AddModelError("FileName", "An error occured, try again");
                    }
                }
                else
                {
                    ModelState.AddModelError("FileName", "The file must be gif, png, jpeg or jpg amd less than 2MB");
                }
            }            
            if (ModelState.IsValid)
            {
                Car car = DB.GetEntityById<Car>(carCreateViewModel.CarID) as Car;
                car.Brand = carCreateViewModel.Brand;
                car.Grade = carCreateViewModel.SelectedGrade;
                car.DoorCount = carCreateViewModel.DoorCount;
                car.EngineType = carCreateViewModel.SelectedEngineType;
                car.FuelConsumption = carCreateViewModel.FuelConsumption;
                car.HasAirConditioning = carCreateViewModel.HasAirConditioning;
                car.LuggageCount = carCreateViewModel.LuggageCount;
                car.Model = carCreateViewModel.Model;
                car.PassangerCount = carCreateViewModel.PassangerCount;
                car.TransmissionType = carCreateViewModel.SelectedTransmissionType;
                car.BrandModel = carCreateViewModel.Brand + " " + carCreateViewModel.Model;

                if (file != null)
                    car.FileName = file.FileName;
               
                DB.Update<Car>(car.ID);

                return RedirectToAction("Index");
            }
            else
            {
                carCreateViewModel.BrandsList = new SelectList(DB.GetList<Brand>().ToList(), "ID", "Name");
                return View(carCreateViewModel);
            }
        }

        //return view with archive confirmation
        [HttpGet]
        public ActionResult Archive(string idUrl)
        {
            try
            {
                int id = int.Parse(idUrl);

                var car = DB.GetEntityById<Car>(id) as Car;
                if (car != null)
                {
                    if (!car.Archived)
                    {
                        return View(car);
                    }
                    else
                    {
                        car.Archived = false;
                        DB.Update<Car>(car.ID);
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    return RedirectToAction("CarNotFound", "Error");
                }
            }
            catch (ArgumentException)
            {
                return RedirectToAction("WrongUrl", "Error");
            }
            catch (FormatException)
            {
                return RedirectToAction("WrongUrl", "Error");
            }
        }

        //archive car
        [HttpGet]
        public ActionResult ArchiveConfirmed(string idUrl)
        {
            try
            {
                int id = int.Parse(idUrl);

                var car = DB.GetEntityById<Car>(id) as Car;
                if (car != null)
                {
                    car.Archived = true;
                    DB.Update<Car>(car.ID);
                    return RedirectToAction("Index");
                }
                else
                {

CarRent/CarRent/Controllers/OfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Entities;
using DataBase;
using CarRent.ViewModels;

namespace CarRent.Controllers
{
    public class OfficeController : Controller
    { 
        private readonly DB DB;

        public OfficeController(DB Db)
        {
            DB = Db;
        }
        public OfficeController()
        {
            DB = new DB();
        }

        public ActionResult Index()
        {
            var cities = DB.GetList<City>().ToList();
            var offices = DB.GetList<Office>().OrderBy(o => o.IsArchived).ToList();
            var viewModel = new List<OfficeIndexViewModel>() { };

            foreach(var city in cities)
            {
                viewModel.Add(new OfficeIndexViewModel()
                {
                    Amount = offices.Where(o => o.CityID == city.ID).Count(),
                    City = city
                });
            }
         
            return View(viewModel);
        }

        //download offices to ajax
        public ActionResult ViewOffices(string idUrl)
        {
            try
            {
                int cityID = int.Parse(idUrl);
                var city = DB.GetEntityById<City>(cityID) as City;

                if(city != null)
                {
                    var offices = DB.GetList<Office>()
                        .Where(o => o.CityID == cityID)
                        .ToList();

                    if(offices == null)
                    {
                        offices = new List<Office>();
                    }

                    var viewModel = new OfficeInCityCiewModel()
                    {
                        Offices = offices,
                        City = city
                    };

                    return View(viewModel);
                }
                else
                {
                    return RedirectToAction("CityNotFound", "Error");
                }

            }
            catch (ArgumentException)
            {
                return RedirectToAction("WrongUrl", "Error");
            }
            catch (FormatException)
            {
                return RedirectToAction("WrongUrl", "Error");
            }
        }

        [HttpGet]
        public ActionResult Create(string idUrl)
        {
            try
            {
                int cityID = int.Parse(idUrl);
                var city = DB.GetEntityById<City>(cityID) as City;

                if (city != null)
                {
                    var office = new Office()
                    {
                        CityID = cityID
                    };

                    return View(office);
                }
                else
                {
                    return RedirectToAction("CityNotFound", "Error");
                }

            }
            catch (ArgumentException)
            {
                return RedirectToAction("WrongUrl", "Error");
            }
            catch (FormatException)
            {
                return RedirectToAction("WrongUrl", "Error");
            }
        }
        
        [HttpPost]
        public ActionResult Create(Office office)
        {
            if(office != null)
            {
                DB.Save<Office>(office);

                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("CityNotFound", "Error");
            }

        }

        [HttpGet]
        public ActionResult Edit(string idUrl)
        {
            try
            {
                int officeID = int.Parse(idUrl);
                var office = DB.GetEntityById<Office>(officeID) as Office;

                if (office != null)
                {                
                    return View(office);
                }
                else
                {
                    return RedirectToAction("OfficeNotFound", "Error");
                }

            }
            catch (ArgumentException)
            {
                return RedirectToAction("WrongUrl", "Error");
            }
            catch (FormatException)
            {
                return RedirectToAction("WrongUrl", "Error");
            }
        }

        [HttpPost]
        public ActionResult Edit(Office office)
        {
            if(office != null)
            {
                var officeToUpdate = DB.GetEntityById<Office>(office.ID) as Office;
                officeToUpdate.PhoneNumber = office.PhoneNumber;
                officeToUpdate.PlaceDescription = office.PlaceDescription;
                officeToUpdate.Address = office.Address;

                DB.Update<Office>(officeToUpdate.ID);

                //return RedirectToAction("Index");
                return RedirectToAction("ViewOffices", new { idUrl = office.CityID.ToString() });
            }
            else
            {
                return RedirectToAction("OfficeNotFound", "Error");
            }
        }

        //archive office
        public ActionResult Archive(string idUrl)
        {
            try
            {
                int officeID = int.Parse(idUrl);
                var office = DB.GetEntityById<Office>(officeID) as Office;

                if (office != null)
                {
                    if (office.IsArchived)
                    {
                        office.IsArchived = false;
                    }
                    else
                    {
                        office.IsArchived = true;
                    }
                    DB.Update<Office>(office.ID);

                    //return RedirectToAction("Index");
                    return RedirectToAction("ViewOffices", new { idUrl = office.CityID.ToString() });
                }
                else
                {
                    return RedirectToAction("OfficeNotFound", "Error");
                }

            }
            catch (ArgumentException)
            {
                return RedirectToAction("WrongUrl", "Error");
            }
            catch (FormatException)
            {
                return RedirectToAction("WrongUrl", "Error");
            }
        }
    }
}

CarRent/CarRent/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CarRent", "CarList", "User", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cars", "Index", "Car")</li>
                    <li>@Html.ActionLink("Additional options", "Index", "AdditionalOption")</li>
                    <li>@Html.ActionLink("Managers", "Index", "ManagerEdit")</li>
                    <li>@Html.ActionLink("Users", "UserList", "Admin")</li>
                    <li>@Html.ActionLink("Stock", "CitiesStock", "Stock")</li>
                    <li>@Html.ActionLink("Offices", "Index", "Office")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid">
        @RenderBody()
        <footer>
            @* <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>


    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CarRent/CarRent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CarRent", "CarList", "User", new { area = "" }, new { @class = "navbar-brand" })

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Rent Rules", "RentRules", "User")</li>
                    <li>@Html.ActionLink("Contacts", "Contacts", "User")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid">
        @RenderBody()
        <footer>
            @* <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>


    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CarRent/CarRent/Views/Shared/_ManagerLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CarRent", "CarList", "User", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Orders", "Orders", "Manger")</li>
                    <li>@Html.ActionLink("Payment", "Index", "Payment")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid">
        @RenderBody()
        <footer>
        </footer>
    </div>


    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>