CarRent/CarRent/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace CarRent.Models
{
    public class IndexViewModel
    {


        [Required]
        [Display(Name = "First Name")]
        [StringLength(20, ErrorMessage = "Name lenght must be between 2 and 20 characters")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Surname")]
        [StringLength(20, ErrorMessage = "Surname lenght must be between 2 and 20 characters")]
        public string LastName { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

CarRent/CarRent/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Entities;
using DataBase;
using Newtonsoft.Json;
using CarRent.ViewModels;
using CarRent.VO;
using Microsoft.AspNet.Identity;

namespace CarRent.Controllers
{
    [Authorize(Roles = "moderator")]
    public class ManagerController : Controller
    {
        private readonly DB DB;

        public ManagerController(DB Db)
        {
            DB = Db;
        }
        public ManagerController()
        {
            DB = new DB();
        }

        ManagerControllerVO vo = new ManagerControllerVO();

        public ActionResult Orders()
        {
            var viewModel = new OrderListViewModel()
            {
                Statuses = new MultiSelectList(Enumerations.Statuses)
            };

            vo.OrderPageShown();

            return View(viewModel);
        }

        //download orders to ajax
        public ActionResult GetOrdersList(string search, List<string> SelectedStatuses)
        {
            var orders = DB.GetList<Order>().ToList();
            var offices = DB.GetList<Office>().ToList();
            var viewModels = new List<ManagerOrderViewModel>();

            if (!String.IsNullOrEmpty(search))
            {
                orders = orders.Where(o => o.User.FirstName.ToLower().Contains(search) 
                || o.User.LastName.ToLower().Contains(search) 
                || o.ID.ToString().Contains(search)).ToList();
            }

            if (SelectedStatuses != null)
            {
                var temp = new List<Order>();
                foreach (var order in orders)
                {
                    if (SelectedStatuses.Contains(order.Status))
                        temp.Add(order);
                }
                orders = temp;
            }

            foreach(var order in orders)
            {
                string color = "";
                switch (order.Status)
                {
                    case "Waiting for manager review":
                        {
                            color = "red";
                        }
                        break;

                    case "Waiting for customer confirm":
                        {
                            color = "blue";
                        }
                        break;

                    case "Waiting for execution":
                        {
                            color = "green";
                        }
                        break;
                    case "On execution":
                        {
                            color = "purple";
                        }
                        break;
                    case "Denied":
                        {
                            color = "gray";
                        }
                        break;
                    case "Executed":
                        {
                            color = "gray";
                        }
                        break;
                }

                viewModels.Add(new ManagerOrderViewModel()
                {
                    ID = order.ID,
                    User = order.User,
                    Car = order.Car,
                    AdditionalOptions = JsonConvert.DeserializeObject<List<AdditionalOption>>(order.AdditionalOptionsJson),
                    OrderDateTime = order.OrderDateTime,
                    RentStartDateTime = order.RentStartDateTime,
                    RentFinishDateTime = order.RentFinishDateTime,
                    OfficeStart = offices.SingleOrDefault(o => o.ID == order.OfficeIdStart),
                    OfficeEnd = offices.SingleOrDefault(o => o.ID == order.OfficeIdEnd),
                    Comment = order.Comment,
                    Price = order.Price,
                    Status = order.Status,
                    Color = color
                });
            }

            vo.OrdersDownloaded(viewModels.Select(vm => vm.ID).ToList());

            return PartialView(viewModels);
        }

        //return view vith managing info
        public ActionResult Manage(string idUrl)
        {
            try
            {
                int id = int.Parse(idUrl);

                var order = DB.GetEntityById<Order>(id) as Order;

                if (order != null)
                {
                    var offices = DB.GetList<Office>().ToList();
                    var orders = DB.GetList<Order>().Where(o => o.UserID == order.UserID).ToList();


                    var problems = DB.GetList<OrderProblem>().ToList();
                    foreach(var problem in problems)
                    {
                        problem.Order = DB.GetEntityById<Order>(problem.Order_ID) as Order;
                    }


                    var orderProblemViewModels = new List<OrderProblemViewModel>();

                    order.OfficeStart = offices.SingleOrDefault(o => o.ID == order.OfficeIdStart);
                    order.OfficeEnd = offices.SingleOrDefault(o => o.ID == order.OfficeIdEnd);

                    foreach(var ord in orders)
                    {
                        var problem = problems.SingleOrDefault(p => p.Order_ID == ord.ID);
                        var problemText = "No problems";
                        var fine = "";
                        if(problem != null)
                        {
                            problemText = problem.Text;
                            fine = problem.Fine.ToString();
                        }

                        var orderProblemViewModel = new OrderProblemViewModel()
                        {
                            ID = ord.ID,
                            BrandModel = ord.Car.BrandModel,
                            Price = ord.Price,
                            Status = ord.Status,
                            UserName = ord.User.FirstName + " " + ord.User.LastName,
                            Problem = problemText,
                            Fine = fine
                        };

                        orderProblemViewModels.Add(orderProblemViewModel);
                    }


                    var viewModel = new OrderManageViewModel()
                    {
                        CurrentOrder = order,
                        User = order.User,
                        OrderConfirmDeny = DB.GetList<OrderConfirmDeny>().SingleOrDefault(ocd => ocd.OrderID == order.ID) ?? new OrderConfirmDeny(),
                        OrderProblemViewModelsUserOrders = orderProblemViewModels,
                        AdditionalOptions = JsonConvert.DeserializeObject<List<AdditionalOption>>(order.AdditionalOptionsJson),
                        OrderProblem = DB.GetList<OrderProblem>().SingleOrDefault(op => op.Order_ID == order.ID)
                    };

                    vo.OrderPassedForManaging();

                    return View(viewModel);
                }
                else
                {
                    vo.OrderNotFound(idUrl);

                    return RedirectToAction("OrderNotFound", "Error");
                }
            }
            catch (ArgumentException)
            {
                vo.WrongUrl(idUrl);

                return RedirectToAction("WrongUrl", "Error");
            }
            catch (FormatException)
            {
                vo.WrongUrl(idUrl);

                return RedirectToAction("WrongUrl", "Error");
            }
        }

        //update status of order
        public ActionResult UpdateStatus(string idUrl, string cityID, int? stockId)
        {
            try
            {
                int id = int.Parse(idUrl);
               
                var order = DB.GetEntityById<Order>(id) as Order;
                order.OfficeEnd = DB.GetEntityById<Office>(order.OfficeIdEnd) as Office;
              
                if (order != null)
                {
                    switch (order.Status)
                    {
                        case "Waiting for manager review":
                            {
                                order.Status = "Waiting for customer confirm";
                                DB.Update<Order>(order.ID);

                                vo.ChangeStatus("Waiting for customer confirm");
                            }
                            break;                  

                        case "Waiting for customer confirm":
                            {                                      
                                order.Status = "Waiting for execution";
                                DB.Update<Order>(order.ID);

                                vo.ChangeStatus("Waiting for execution");
                            }
                            break;

                        case "Waiting for execution":
                            {
                                var user = DB.GetEntityById<ApplicationUser>(order.UserID) as ApplicationUser;
                                if(user.Debt > 0 || user.Fine > 0)
                                {
                                    int amount = user.Debt + user.Fine;
                                    return RedirectToAction("UserHasDebt", "Error", new { amount = amount });
                                }

                                order.Status = "On execution";
                                DB.Update<Order>(order.ID);

                                vo.ChangeStatus("On execution");
                            }
                            break;

                        case "On execution":
                            {
                                if (stockId != null)
                                {
                                    order.Status = "Executed";
                                    order.IsArchived = true;
                                    DB.Update<Order>(order.ID);

                                    var stock = DB.GetEntityById<Stock>((int)stockId) as Stock;
                                    stock.IsBusy = false;

CarRent/CarRent/Views/Manager/GetOrdersList.cshtml
@model IEnumerable<CarRent.ViewModels.ManagerOrderViewModel>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Car)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OfficeStart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RentStartDateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OfficeEnd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RentFinishDateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(model => item.ID)
        </td>
        <td style="color:@item.Color">
            @Html.DisplayFor(model => item.Status)
        </td>
        <td>
            @(item.User.FirstName + " " + item.User.LastName)
        </td>
        <td>
            @(item.Car.BrandModel)
        </td>
        <td>
            @(item.OrderDateTime.ToShortDateString() + " " + item.OrderDateTime.ToShortTimeString())
        </td>
        <td>
            @Html.DisplayFor(model => item.OfficeStart.PlaceDescription)
        </td>
        <td>
            @(item.RentStartDateTime.ToShortDateString() + " " + item.RentStartDateTime.ToShortTimeString())
        </td>
         <td>
            @Html.DisplayFor(model => item.OfficeEnd.PlaceDescription)
        </td>
        <td>
            @(item.RentFinishDateTime.ToShortDateString() + " " + item.RentFinishDateTime.ToShortTimeString())
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Manage", "Manage", new { idUrl=item.ID.ToString() })
        </td>
    </tr>
}

</table>

CarRent/CarRent/Views/Manager/Manage.cshtml
@model CarRent.ViewModels.OrderManageViewModel
@{
    ViewBag.Title = "Manage";
    Layout = "~/Views/Shared/_ManagerLayout.cshtml";
}

<h2>Managing order</h2>

<div class="row">
    <div class="col-md-3">
        <h3 class="col-md-offset-2">Current order</h3>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(m => m.CurrentOrder.ID)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.CurrentOrder.ID)
            </dd>

            <dt>
                @Html.DisplayNameFor(m => m.CurrentOrder.Status)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.CurrentOrder.Status)
            </dd>

            <dt>
                @Html.DisplayNameFor(m => m.CurrentOrder.User)
            </dt>
            <dd>
                @(Model.User.FirstName + " " + Model.User.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(m => m.CurrentOrder.Car)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.CurrentOrder.Car.BrandModel)
            </dd>

            <dt>
                Order DateTime
            </dt>
            <dd>
                @(Model.CurrentOrder.OrderDateTime.ToShortDateString() + " " + Model.CurrentOrder.OrderDateTime.ToShortTimeString())
            </dd>

            <dt>
                Office Start
            </dt>
            <dd>
                @Model.CurrentOrder.OfficeStart.PlaceDescription
            </dd>

            <dt>
                Rent Start DateTime
            </dt>
            <dd>
                @(Model.CurrentOrder.RentStartDateTime.ToShortDateString() + " " + Model.CurrentOrder.RentStartDateTime.ToShortTimeString())
            </dd>

            <dt>
                Office End
            </dt>
            <dd>
                @Model.CurrentOrder.OfficeEnd.PlaceDescription
            </dd>

            <dt>
                Rent Finish DateTime
            </dt>
            <dd>
                @(Model.CurrentOrder.RentFinishDateTime.ToShortDateString() + " " + Model.CurrentOrder.RentFinishDateTime.ToShortTimeString())
            </dd>

            <dt>
                Additional options
            </dt>
            <dd>
                @foreach (var option in Model.AdditionalOptions)
                {
                    @option.Name <br />
                }
            </dd>

            <dt>
                Status
            </dt>
            <dd>
                @Model.CurrentOrder.Status
            </dd>

            <dt>
                Stock Id
            </dt>
            <dd>
                @Model.CurrentOrder.StockID
            </dd>
            <dt>
                Comment
            </dt>
            <dd>
                @Html.DisplayFor(m => m.CurrentOrder.Comment)
            </dd>

            <dt>
                Price
            </dt>
            <dd>
                @Html.DisplayFor(m => m.CurrentOrder.Price)
            </dd>
        </dl>
    </div>

    <div class="col-md-3">
        <h3 class="col-md-offset-2">Current user</h3>
        <dl class="dl-horizontal">
            <dt>
                First Name
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User.FirstName)
            </dd>

            <dt>
                Last Name
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User.LastName)
            </dd>

            <dt>
                Email
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User.Email)
            </dd>

            <dt>
                Birth Date
            </dt>

            <dd>
                @Html.DisplayFor(model => Model.User.BirthDate)
            </dd>

            <dt>
                Driving Liscense Date
            </dt>

            <dd>
                @Html.DisplayFor(model => Model.User.DrivingLicenseDate)
            </dd>

            <dt>
                ID Number
            </dt>

            <dd>
                @Html.DisplayFor(model => Model.User.IDNumber)
            </dd>

            <dt>
                Phone Number
            </dt>

            <dd>
                @Html.DisplayFor(model => Model.User.PhoneNumber)
            </dd>
        </dl>
    </div>

    <div class="col-md-6">
        <h3>All customer orders</h3>
        <table class="table">
            <tr>
                <th>ID</th>
                <th>User Name</th>
                <th>Car</th>
                <th>Price</th>
                <th>Status</th>
                <th>Problem</th>
                <th>Fine</th>
            </tr>
            @foreach (var item in Model.OrderProblemViewModelsUserOrders)
            {
                <tr>
                    <td>@item.ID</td>
                    <td>@item.UserName</td>
                    <td>@item.BrandModel</td>
                    <td>@item.Price</td>
                    <td>@item.Status</td>
                    <td>@item.Problem</td>
                    <td>@item.Fine</td>
                </tr>
            }
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        @switch (Model.CurrentOrder.Status)
        {
            case "Waiting for manager review":
                {
                    <div class="col-md-offset-2">
                        <h4>Current status - @Model.CurrentOrder.Status</h4>
                        <h4>Next status - Waiting for customer confirm</h4>
                        @Html.ActionLink("Update Status", "UpdateStatus", "Manager", new { idUrl = Model.CurrentOrder.ID.ToString() }, htmlAttributes: new { @class = "btn btn-primary" }) <hr />

                        @using (Html.BeginForm("DenyOrder", "Manager"))
                        {
                            <h5>Deny reason</h5>
                            @Html.TextBoxFor(m => m.OrderConfirmDeny.Text, new { @class = "form-control reasonDeny" })
                            @Html.HiddenFor(m => m.OrderConfirmDeny.OrderID, new { id = "OrderID", Value = Model.CurrentOrder.ID })
                            @Html.HiddenFor(m => m.CurrentOrder.StockID)
                            <h6 class="error text-danger">Reason lenght must be between 10 and 100 characters</h6>
                            <br />
                            <input type="submit" value="Deny" class="btn btn-danger deny" />
                        }
                    </div>
                }
                break;

            case "Denied":
                {
                    <div class="col-md-offset-2">
                        <h4>This order has been denied <br />Reason - @Model.OrderConfirmDeny.Text</h4>
                    </div>
                }
                break;

            case "Waiting for customer confirm":
                {
                    <div class="col-md-offset-2">
                        <h4>Current status - @Model.CurrentOrder.Status</h4>
                        <h4>Next status - Waiting for execution</h4>
                        @Html.ActionLink("Update Status", "UpdateStatus", "Manager", new { idUrl = Model.CurrentOrder.ID.ToString(), carID = Model.CurrentOrder.CarID.ToString(), cityID = Model.CurrentOrder.OfficeStart.CityID.ToString() }, htmlAttributes: new { @class = "btn btn-primary" }) <hr />

                        @using (Html.BeginForm("DenyOrder", "Manager"))
                        {
                            <h5>Deny reason</h5>
                            @Html.TextBoxFor(m => m.OrderConfirmDeny.Text, new { @class = "form-control reasonDeny" })
                            @Html.HiddenFor(m => m.OrderConfirmDeny.OrderID, new { id = "OrderID", Value = Model.CurrentOrder.ID })
                            @Html.HiddenFor(m => m.CurrentOrder.StockID)
                            <h6 class="error text-danger">Reason lenght must be between 10 and 100 characters</h6>
                            <br />
                            <input type="submit" value="Deny" class="btn btn-danger deny" />
                        }
                    </div>
                }
                break;

            case "Waiting for execution":
                {
                    <div class="col-md-offset-2">
                        <h4>Current status - @Model.CurrentOrder.Status</h4>
                        <h4>Next status - On Execution</h4>
                        @Html.ActionLink("Update Status", "UpdateStatus", "Manager", new { idUrl = Model.CurrentOrder.ID.ToString() }, htmlAttributes: new { @class = "btn btn-primary" }) <hr />

                        @using (Html.BeginForm("DenyOrder", "Manager"))
                        {
                            <h5>Deny reason</h5>
                            @Html.TextBoxFor(m => m.OrderConfirmDeny.Text, new { @class = "form-control reasonDeny" })
                            @Html.HiddenFor(m => m.OrderConfirmDeny.OrderID, new { id = "OrderID", Value = Model.CurrentOrder.ID })
                            @Html.HiddenFor(m => m.CurrentOrder.StockID)
                            <h6 class="error text-danger">Reason lenght must be between 10 and 100 characters</h6>
                            <br />
                            <input type="submit" value="Deny" class="btn btn-danger deny" />
                        }
                    </div>
                }
                break;

            case "On execution":
                {
                    <div class="col-md-offset-2">
                        <div class="col-md-6">
                            <h4>Current status - @Model.CurrentOrder.Status</h4>
                            <h4>Next status - Executed</h4>
                            @Html.ActionLink("Update Status", "UpdateStatus", "Manager", new { idUrl = Model.CurrentOrder.ID.ToString(), stockId = Model.CurrentOrder.StockID}, htmlAttributes: new { @class = "btn btn-primary" }) <hr />
                        </div>
                        <div class="col-md-6">
                            @using (Html.BeginForm("OrderProblem", "Manager"))
                            {
                                <h4>If there were any car damage or other issues, fill this form</h4>
                                @Html.TextBoxFor(m => m.OrderProblem.Text, new { @class = "form-control reason" })
                                <h6 class="error text-danger">Reason lenght must be between 10 and 100 characters</h6>

                                <br />

                                @Html.TextBoxFor(m => m.OrderProblem.Fine, new { @class = "form-control fine" })
                                <h6 class="errorFine text-danger">Fine bust be between 1 and 10000$</h6>

                                @Html.HiddenFor(m => m.OrderConfirmDeny.OrderID, new { id = "OrderID", Value = Model.CurrentOrder.ID })
                                @Html.HiddenFor(m => m.CurrentOrder.StockID)
                                @Html.HiddenFor(m => m.CurrentOrder.UserID)

                                <br />
                                <input type="submit" value="Register problem" class="btn btn-danger denyProblem" />
                            }
                        </div>
                    </div>
                }
                break;

            case "Executed":
                {
                    <div class="col-md-offset-2">
                        @if(Model.OrderProblem == null)
                        {
                            <h4>This order has been executed without any issues</h4>
                        }
                        else
                        {
                            <h3 class="text-danger">There was an issue in this order: <br /></h3>
                            <h4>Reason - @Model.OrderProblem.Text <br />Fine - @Model.OrderProblem.Fine</h4>
                        }
                    </div>
                }
                break;
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    $(function () {
        $('.error').hide();
        $('.errorFine').hide();

        $('.reason').focusout(reasonValidate);
        $('.fine').focusout(fineValidate);
        $('.reasonDeny').focusout(reasonValidateDeny);

        function reasonValidate() {
            $('.error').hide();
            if ($('.reason').val().length <= 10 || $('.reason').val().length >= 100) {
                $('.error').show();
            }
        }

        function fineValidate() {
            $('.errorFine').hide();
                if (isNaN(parseInt($('.fine').val())) || parseInt($('.fine').val()) <= 1 || parseInt($('.fine').val()) >= 10000) {
                    $('.errorFine').show();
                }
        }

        function reasonValidateDeny() {
            $('.error').hide();
            if ($('.reasonDeny').val().length <= 10 || $('.reasonDeny').val().length >= 100) {
                $('.error').show();
            }
        }

        $('.denyProblem').click(function (e) {         
            reasonValidate();
            fineValidate();

            if (!$('.error').is(":hidden") || !$('.errorFine').is(":hidden")) {
                e.preventDefault();
            }
        });

         $('.deny').click(function (e) {         
             reasonValidateDeny();

            if (!$('.error').is(":hidden")) {
                e.preventDefault();
            }
        });
    });
</script>

CarRent/CarRent/Views/Manager/Orders.cshtml
@model CarRent.ViewModels.OrderListViewModel
@{
    ViewBag.Title = "Orders";
        Layout = "~/Views/Shared/_ManagerLayout.cshtml";
}

<h2>Orders</h2>

@using(Ajax.BeginForm("GetOrdersList", "Manager", null, new AjaxOptions() { UpdateTargetId = "results" }))
{
    <div class="form-group col-md-2">
        @Html.TextBox("search", null, new { @class = "form-control", @placeholder = "Search User" })
    </div>

    <div class="panel-group col-md-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#collapseGrades">Statuses</a>
                </h4>
            </div>
            <div id="collapseGrades" class="panel-collapse collapse">
                @Html.ListBoxFor(m => m.SelectedStatuses, Model.Statuses, new { @class = " form-control list-group" })
            </div>
        </div>
    </div>

    <button type="submit" class="btn btn-default">Update</button>
}


<div id="results">
    @Html.Action("GetOrdersList")
</div>